############################################################
# Script Name:    ExtractSpectralLines.R
# Author:         Patrick Byron Angst
# Date Created:   2025-09-30
# Last Modified:  2025-09-30
# Version:        1.0
#
# Description:    This is a wrapper script to batch process multiple test sites.
#                 It sources the main function from 'ExtractSpectralLines_Script.R',
#                 identifies all test site folders, and then calls the spectral
#                 extraction function for each site in a loop.
#
# Dependencies:   Relies on 'ExtractSpectralLines_Script.R' which contains the
#                 necessary function and its own library dependencies.
#
# Input Files:    - The folder structure within 'data/MasterThesis/final_hs_data_folder/'.
#                   The script uses the names of the subdirectories as input for the function.
#
# Output Files:   - Status messages printed to the console (e.g., "AN_TJ_1 done").
#                 - All file outputs (CSVs and PNGs) are generated by the sourced script.
#
# License:        MIT
############################################################

# clean environment
rm(list = ls(all = TRUE))
gc()
graphics.off()

source('ExtractSpectralLines_Script.R')

# testsite_name <- 'AN_TJ_1'
# x_axis_intervall <- 50
# pixel_buffer <- 5 # Buffer in meters around the coordinates to calculate the mean reflectance value



folder_names <- folder_names <- list.dirs("data/MasterThesis/final_hs_data_folder", full.names = FALSE, recursive = FALSE)

for (name in folder_names) {
  # debug(extract_spectral_signature)
  extract_spectral_signature(name)

  print(paste0(name, " done"))
}
